### ISSUE TITLE
Create a backend for css processing

### ISSUE THREAD

**Issue by stealthanthrax** [SiddharthSham/cssify#2]
We'll require a backend which will accept the user response and create the custom css framework to respond back to the user.

**Comment by SiddharthSham** [comment]
Alright, we'll have the backend accept configuration details in the form of a JSON object. That'll make making the custom builds easier.

For now, I think custom variable support should be our first priority. Because I'm not completely sure as to how to pull off custom imports.

I'll be using Express for the backend.

**Comment by SiddharthSham** [comment]
Commit 4bad046c908f66dbb7a2638c62c2f825860237b6 adds the backend :D
